

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 12345678
  host: localhost


development:
  <<: *default
  database: myapp_development

 
test:
  <<: *default
  database: myapp_test


  production:
  <<: *default
  url: mysql2://bae5c45e471146:0b37ff63@us-cdbr-east-06.cleardb.net/heroku_8df85e809f1ba3f?reconnect=true


